stages:
    - build

build_job:
    stage: build
    only:
        - branches
    script:
        - '"D:\Programs\Nuget\nuget.exe" restore'
        - '& "D:\Programs\Microsoft\Visual Studio Enterprise 2019\MSBuild\Current\Bin\MSBuild.exe" ConsoleApp2.sln'
    artifacts:
        paths:
            - 'C:\Users\Victor\AndroidStudioProjects\2\ConsoleApp2\ConsoleApp2\bin\Debug\netcoreapp3.1\ConsoleApp2.exe'
